version: '3'

services:
  web:
    container_name: subscriber
    build: ./DeribitFutureSubscriber/
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=MarketData2
    ports:
      - 5432:5432

  