version: '3'

services:
  api:
    container_name: api
    build: ./DeribitFutureAPI/
    depends_on:
      - postgres
    ports:
      - 50608:50608

  subscriber:
    container_name: subscriber
    build: ./DeribitFutureSubscriber/
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=MarketData2
    ports:
      - 5432:5432

volumes:
  db:

  